#!/bin/zsh -eu

# >>>>> Claude Code 工具
bun add -g @anthropic-ai/claude-code@latest

cat <<'EOF' >> ~/.zshrc
alias claude='bunx --bun -g claude --dangerously-skip-permissions'
export DEVCONTAINER=true
EOF

cat <<'EOF' > ~/.claude.json
{
  "numStartups": 1,
  "theme": "light-daltonized",
  "bypassPermissionsModeAccepted": true,
  "hasCompletedOnboarding": true
}
EOF


# >>>>>> Gemini CLI 工具
bun add -g @google/gemini-cli@latest
cat <<'EOF' >> ~/.zshrc
alias gemini='bunx --bun -g gemini --yolo -m gemini-2.5-pro'
export SANDBOX=h-devcontainer
EOF

mkdir -p ~/.gemini || true
cat <<'EOF' > ~/.gemini/settings.json
{
  "security": {
    "auth": {
      "selectedType": "gemini-api-key"
    }
  },
  "ide": {
    "enabled": true
  }
}
EOF
