[program:code-server]
command=/usr/local/bin-priority/code-server --config /vscode/code-server/config.yaml --bind-addr 0.0.0.0:8443 --auth none --disable-telemetry /workspaces
directory=/workspaces
user=usr_vscode
autostart=true
autorestart=true
startsecs=5
startretries=3
stopsignal=TERM
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/code-server.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
environment=HOME="/home/usr_vscode",SHELL="/bin/zsh",USER="usr_vscode",LOGNAME="usr_vscode"
