#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# arp: 查看和管理 ARP 缓存
# 示例：
arp -a                           # 显示所有 ARP 条目
arp -n                            # 以数字格式显示
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: arp --version 2>&1 | head -1
exec _apt-shim-exec net-tools arp "$@"
