#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# arpd: 用户空间 ARP 守护进程
# 示例：
arpd -l                          # 列出 ARP 缓存
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: arpd -V 2>&1 | head -1
exec _apt-shim-exec iproute2 arpd "$@"
