#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

# @verify: bash-language-server --version

add-bun-priority-bin-pkg bash-language-server@latest

BUN_ARGS=("--bun")
BUN_ARGS+=("run")
BUN_ARGS+=("/vscode/bun-priority-bin/node_modules/.bin/bash-language-server")

echo -e "\e[90m→ exec bun ${BUN_ARGS[*]} $*\e[0m" >&2

exec bun "${BUN_ARGS[@]}" "$@"
