#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# 示例：
bats tests/
#-------------------------------------------------------------------------------------------------------------
fi

if ! dpkg --status bats &>/dev/null; then
  # -E 选项：保留（preserve）当前的环境变量
  sudo -E _execute-remote-script https://Git.1-H.CC/Scripts/Linux/raw/branch/2026/devcontainer/apt-install-with-cache.sh \
    bats
fi

# 跳过自身，找到真实的 bats 可执行文件
real_bats="$(_get-real-bin bats || true)"

if [ -z "$real_bats" ]; then
    echo "❌ Error: Failed to find real bats executable" >&2
    exit 1
fi

exec "$real_bats" "$@"