#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# 示例：
bats tests/
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: bats --version
exec _apt-shim-exec bats bats "$@"