#!/bin/sh
# https://github.com/devcontainers/features/blob/main/src/common-utils/bin/code
# https://github.com/devcontainers/features/blob/b0188f0a5ef98f1c3217b6c0fe14c3ee472fad68/src/common-utils/main.sh#L599-L601
# code shim, it fallbacks to code-insiders if code is not available

# 容许找不到 code，fallback 到 code-insiders
code="$(_get-real-bin code 2>/dev/null)" || true

if [ -n "$code" ]; then
    exec "$code" "$@"
elif [ "$(command -v code-insiders)" ]; then
    exec code-insiders "$@"
else
    echo "code or code-insiders is not installed" >&2
    exit 127
fi