#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# ctstat: 连接跟踪统计（lnstat 别名）
# 示例：
ctstat                           # 显示连接跟踪统计
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: ctstat -V 2>&1 | head -1
exec _apt-shim-exec iproute2 ctstat "$@"
