#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# dcb: 数据中心桥接管理
# 示例：
dcb show dev eth0                # 显示 DCB 配置
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: dcb -V 2>&1 | head -1
exec _apt-shim-exec iproute2 dcb "$@"
