#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# 示例：
echo "可以在这里写示例，现在没有噢。"
#-------------------------------------------------------------------------------------------------------------
fi

if ! dpkg --status file &>/dev/null; then
  _apt-install-cached file
fi

# 跳过自身，找到真实的 file 可执行文件
real_file=$(which -a file | grep -v '/usr/local/bin-priority/' | head -n1)
exec "$real_file" "$@"
