#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# 示例：
echo "可以在这里写示例，现在没有噢。"
#-------------------------------------------------------------------------------------------------------------
fi

if ! dpkg --status file &>/dev/null; then
  _apt-install-cached file
fi

exec _exec-real-bin file "$@"
