#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

# @verify: gh --version

if false; then
#-------------------------------------------------------------------------------------------------------------
# 示例：
gh auth status
gh auth login

# ~/.config/gh/hosts.yml
# github.com:
#     users:
#         yanhao98:
#             oauth_token: gho_***
#     git_protocol: https
#     oauth_token: gho_***
#     user: yanhao98
#-------------------------------------------------------------------------------------------------------------
fi

_ensure-vscode-symlink /vscode/gh-config ~/.config/gh

if ! dpkg --status gh &>/dev/null; then
  _apt-install-cached gh
fi

exec _exec-real-bin gh "$@"