#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# 示例：
gh auth status
gh auth login

# ~/.config/gh/hosts.yml
# github.com:
#     users:
#         yanhao98:
#             oauth_token: gho_***
#     git_protocol: https
#     oauth_token: gho_***
#     user: yanhao98
#-------------------------------------------------------------------------------------------------------------
fi

_ensure-vscode-symlink /vscode/gh-home ~/.gh

if ! dpkg --status gh &>/dev/null; then
  _apt-install-cached gh
fi

# 跳过自身，找到真实的 gh 可执行文件
real_gh=$(which -a gh | grep -v '/usr/local/bin-priority/' | head -n1)
exec "$real_gh" "$@"