#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# gpg2: GnuPG 2，用于加密、签名和密钥管理
# 示例：
gpg2 --list-keys                     # 列出所有公钥
gpg2 --verify file.sig file          # 验证签名
gpg2 -d file.gpg                     # 解密文件
gpg2 --import key.asc                # 导入密钥
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: gpg2 --version
exec _apt-shim-exec gnupg2 gpg2 "$@"
