#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# ipmaddr: 管理多播地址
# 示例：
ipmaddr show                     # 显示多播地址
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: ipmaddr 2>&1 | head -1
exec _apt-shim-exec net-tools ipmaddr "$@"
