#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# lnstat: 网络接口统计信息监控
# 示例：
lnstat                           # 显示网络统计
lnstat -d                         # 列出可用的统计文件
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: lnstat -V 2>&1 | head -1
exec _apt-shim-exec iproute2 lnstat "$@"
