#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# mandb: 更新手册页索引数据库
# 示例：
mandb                            # 更新手册页索引
mandb -c                          # 从零创建数据库
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: mandb --version 2>&1 | head -1
exec _apt-shim-exec man-db mandb "$@"
