#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# manpath: 显示手册页搜索路径
# 示例：
manpath                          # 显示当前手册页搜索路径
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: manpath --version 2>&1 | head -1
exec _apt-shim-exec man-db manpath "$@"
