#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# mii-tool: 查看网卡协商状态
# 示例：
mii-tool eth0                    # 查看 eth0 的链路状态
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: mii-tool --version 2>&1 | head -1
exec _apt-shim-exec net-tools mii-tool "$@"
