#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# nameif: 基于 MAC 地址命名网络接口
# 示例：
nameif eth0 00:11:22:33:44:55    # 将指定 MAC 的接口命名为 eth0
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: nameif --version 2>&1 | head -1
exec _apt-shim-exec net-tools nameif "$@"
