#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

if false; then
#-------------------------------------------------------------------------------
# nautilus: GNOME 文件管理器
# 示例：
nautilus ~                    # 打开主目录
nautilus /tmp                 # 打开指定目录
#-------------------------------------------------------------------------------
fi

# @verify: nautilus --version
exec _apt-shim-exec nautilus nautilus "$@"
