#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

source /devcontainer/shim-utils.sh
_print_caller_info

if ! dpkg --status python3-pip-whl &>/dev/null; then
  _apt-install-cached python3-pip
fi

exec _exec-real-bin pip3 "$@"
