#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

add-bun-priority-bin-pkg @qwen-code/qwen-code@latest

BUN_ARGS=("--bun")
BUN_ARGS+=("run")
BUN_ARGS+=("/vscode/bun-priority-bin/node_modules/.bin/qwen")
CLI_ARGS=()
CLI_ARGS+=("--yolo")
# CLI_ARGS+=("--show-memory-usage")
CLI_ARGS+=("--experimental-skills")

_ensure-vscode-symlink /vscode/qwen-home ~/.qwen

echo -e "\e[90m→ exec bun ${BUN_ARGS[*]} ${CLI_ARGS[*]} $*\e[0m" >&2
# bun --bun --cwd=/vscode/bun-priority-bin/ run iflow --version

exec bun "${BUN_ARGS[@]}" "${CLI_ARGS[@]}" "$@"
