#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if ! dpkg --status rsync &>/dev/null; then
  _apt-install-cached rsync
fi

real_rsync="$(_get-real-bin rsync || true)"

if [ -z "$real_rsync" ]; then
    echo "❌ Error: Failed to find real rsync executable" >&2
    exit 1
fi

exec "$real_rsync" "$@"