#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if ! dpkg --status rsync &>/dev/null; then
  _apt-install-cached rsync
fi

exec _exec-real-bin rsync "$@"