#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if ! dpkg --status rsync &>/dev/null; then
  # -E 选项：保留（preserve）当前的环境变量
  sudo -E _execute-remote-script https://Git.1-H.CC/Scripts/Linux/raw/branch/2026/devcontainer/apt-install-with-cache.sh \
    rsync
fi

real_rsync="$(_get-real-bin rsync || true)"

if [ -z "$real_rsync" ]; then
    echo "❌ Error: Failed to find real rsync executable" >&2
    exit 1
fi

exec "$real_rsync" "$@"