#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# rtacct: 路由统计信息
# 示例：
rtacct                           # 显示路由统计
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: rtacct -V 2>&1 | head -1
exec _apt-shim-exec iproute2 rtacct "$@"
