#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# rtmon: 路由监控
# 示例：
rtmon file /tmp/rtmon.log        # 记录路由变化到文件
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: rtmon -V 2>&1 | head -1
exec _apt-shim-exec iproute2 rtmon "$@"
