#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# rtstat: 路由缓存统计（lnstat 别名）
# 示例：
rtstat                           # 显示路由缓存统计
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: rtstat -V 2>&1 | head -1
exec _apt-shim-exec iproute2 rtstat "$@"
