#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# tc: 流量控制管理
# 示例：
tc qdisc show                    # 显示排队规则
tc -s class show dev eth0         # 显示流量分类统计
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: tc -V 2>&1 | head -1
exec _apt-shim-exec iproute2 tc "$@"
