#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# vdpa: vDPA 设备管理
# 示例：
vdpa dev show                    # 显示 vDPA 设备
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: vdpa -V 2>&1 | head -1
exec _apt-shim-exec iproute2 vdpa "$@"
