#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

if false; then
#-------------------------------------------------------------------------------
# xclip-copyfile: 通过 X 剪贴板复制文件
# 示例：
xclip-copyfile file1.txt file2.txt
#-------------------------------------------------------------------------------
fi

# @verify: which xclip-copyfile
exec _apt-shim-exec xclip xclip-copyfile "$@"
