#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# xzcmp: 比较两个压缩文件是否相同
# 示例：
xzcmp a.xz b.xz                 # 比较两个 .xz 文件是否相同
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: xzcmp --help 2>&1 | head -1
exec _apt-shim-exec xz-utils xzcmp "$@"
