#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# xzless: 分页查看压缩文件内容
# 示例：
xzless file.xz                  # 分页查看 .xz 文件内容
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: xzless --help 2>&1 | head -1
exec _apt-shim-exec xz-utils xzless "$@"
