#!/bin/bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail

if false; then
#-------------------------------------------------------------------------------------------------------------
# xzmore: 分页查看压缩文件内容（类似 more）
# 示例：
xzmore file.xz                  # 分页查看 .xz 文件内容
#-------------------------------------------------------------------------------------------------------------
fi

# @verify: xzmore --help 2>&1 | head -1
exec _apt-shim-exec xz-utils xzmore "$@"
