#!/bin/zsh -eu
echo '↘️ 容器已创建！'

h-setup-zh-locale

h-setup-bun-bin
h-setup-pnpm-bin

h-setup-ai-claude-code --config
h-setup-ai-gemini-cli --config

h-install-node-modules

h-setup-desktop-lite
h-setup-chromium
