#!/usr/bin/env bash
set -o errexit    # 对应 -e
set -o nounset    # 对应 -u
set -o pipefail   # 对应 -o pipefail


# 检查 node_modules 权限
if [ -d "node_modules" ]; then
    sudo chown -R $(whoami) node_modules || true
fi

# 安装依赖
if [ -f "bun.lock" ]; then
    if command -v bun >/dev/null 2>&1; then
        time bun install
    else
        echo '⏭️  跳过: bun 未安装'
    fi
elif [ -f "pnpm-lock.yaml" ]; then
    if command -v pnpm >/dev/null 2>&1; then
        # 跳过: The modules directory at "/workspaces/h-devcontainers/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ·
        time pnpm install --config.confirmModulesPurge=false
    else
        echo '⏭️  跳过: pnpm 未安装'
    fi
else
    echo '⏭️  跳过: 未找到 lock 文件'
fi
