#!/bin/zsh -eu

curl -fsSL https://Git.1-H.CC/Scripts/Linux/raw/branch/2026/devcontainer/apt-install-with-cache.sh | sudo bash -s -- \
  hyperfine

h-setup-zh-locale

h-setup-bun-bin
h-setup-pnpm-bin

h-setup-ai-gemini-cli --config

h-setup-chromium
h-setup-desktop-lite
h-gen-wallpaper

h-install-node-modules

echo "-----------------------------"
echo "开发容器已启动并配置完成！"
echo "-----------------------------"