#!/bin/zsh
# set -o errexit    # 对应 -e
# set -o nounset    # 对应 -u
# set -o pipefail   # 对应 -o pipefail

h-setup-lingma

h-setup-zh-locale

h-setup-bun-bin
h-setup-pnpm-bin

h-setup-desktop-lite
h-gen-wallpaper

h-smart-install-node-modules

echo "-----------------------------"
echo "开发容器已启动并配置完成！"
echo "-----------------------------"