#!/bin/sh
# https://github.com/devcontainers/features/blob/main/src/common-utils/bin/code
# https://github.com/devcontainers/features/blob/b0188f0a5ef98f1c3217b6c0fe14c3ee472fad68/src/common-utils/main.sh#L599-L601
# code shim, it fallbacks to code-insiders if code is not available

get_in_path_except_current() {
    which -a "$1" | grep -A1 "$0" | grep -v "$0"
}
# get_in_path_except_current() {
#     which -a "$1" | while read -r p; do
#         if ! [ "$p" -ef "$0" ]; then
#             echo "$p"
#             break
#         fi
#     done
# }

code="$(get_in_path_except_current code)"

if [ -n "$code" ]; then
    exec "$code" "$@"
elif [ "$(command -v code-insiders)" ]; then
    exec code-insiders "$@"
else
    echo "code or code-insiders is not installed" >&2
    exit 127
fi