#!/bin/bash
#-------------------------------------------------------------------------------------------------------------
# https://github.com/devcontainers/features/blob/main/src/desktop-lite/install.sh
#-------------------------------------------------------------------------------------------------------------
set -euo pipefail

curl -fsSL https://Git.1-H.CC/Scripts/Linux/raw/branch/2026/devcontainer/apt-install-with-cache.sh | sudo bash -s -- \
    tigervnc-standalone-server tigervnc-common tigervnc-tools \
    fluxbox dbus-x11 x11-utils x11-xserver-utils xdg-utils fbautostart \
    at-spi2-core xterm nautilus mousepad seahorse \
    gnome-icon-theme gnome-keyring \
    libx11-dev libxkbfile-dev libsecret-1-dev libgbm-dev libnotify4 \
    libnss3 libxss1 libasound2 libasound2-dev \
    xfonts-base xfonts-terminus fonts-noto fonts-wqy-microhei fonts-droid-fallback fonts-noto-color-emoji \
    htop ncdu curl ca-certificates unzip nano locales \
    python3-minimal python3-numpy \
    tilix

echo "正在从 GitHub 获取并执行 desktop-lite 安装脚本..."

# 使用 curl 下载并执行远程脚本，同时移除清理 apt 缓存的命令
curl -sSL https://raw.githubusercontent.com/devcontainers/features/main/src/desktop-lite/install.sh | \
  sed '\#rm -rf /var/lib/apt/lists/\*#d' | \
  sudo env INSTALL_NOVNC="false" VNC_RESOLUTION="1680x1050x16" bash

# 将名为 VNC-0 的虚拟显示器的分辨率设置为 1920x1200
# xrandr --output VNC-0 --mode 1920x1200

curl -fsSL https://Git.1-H.CC/Scripts/Linux/raw/branch/2026/devcontainer/apt-install-with-cache.sh | sudo bash -s -- \
  chromium chromium-l10n

cat << 'EOF' | sudo tee /usr/local/bin/chromium > /dev/null
#!/bin/bash
exec /usr/bin/chromium --no-sandbox --start-maximized "$@"
EOF
sudo chmod +x /usr/local/bin/chromium

# 启动桌面进程
/usr/local/share/desktop-init.sh
