#!/bin/zsh -eu

# >>>>> Claude Code 工具
# 参考: https://github.com/anthropics/claude-code/blob/1fe9e369a7c30805189cbbb72eb69c15ed4ec96b/.devcontainer/Dockerfile#L42
bun add -g @anthropic-ai/claude-code@latest

# sudo mkdir -p /vscode/claude-config || true
# sudo chown -R $(whoami):$(whoami) /vscode/claude-config || true
cat <<'EOF' >> ~/.zshrc
alias claude='bunx --bun -g claude --dangerously-skip-permissions'
export DEVCONTAINER=true
# export CLAUDE_CONFIG_DIR=/vscode/claude-config
EOF

# cat <<'EOF' > ~/.claude.json
# {
#   "numStartups": 1,
#   "theme": "light-daltonized",
#   "bypassPermissionsModeAccepted": true,
#   "hasCompletedOnboarding": true
# }
# EOF


# >>>>>> Gemini CLI 工具
bun add -g @google/gemini-cli@latest
cat <<'EOF' >> ~/.zshrc
alias gemini='bunx --bun -g gemini --yolo -m gemini-2.5-pro'
export SANDBOX=h-devcontainer
EOF

# mkdir -p ~/.gemini || true
# cat <<'EOF' > ~/.gemini/settings.json
# {
#   "security": {
#     "auth": {
#       "selectedType": "gemini-api-key"
#     }
#   },
#   "ide": {
#     "enabled": true
#   }
# }
# EOF
